sudo: required
dist: trusty
language: node_js
node_js:
  - '10.4.1'

branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - pushd $TRAVIS_BUILD_DIR
  - npm install -g @angular/cli
  - npm install -g karma
  - npm install

script:
  - npm run build
  # - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  # - cp proxy-config.example.json proxy-config.json && npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
